name: playmu
description: "PlayMu Frontend"

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/PlayMu/playmu_desktop

version: 0.1.0+1

environment:
  sdk: ^3.9.2
  flutter: ^3.35.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
